# set up frontend
FROM node as build-stage

WORKDIR /frontend

# copy over project
COPY ./public .
COPY ./src .
COPY ./package-lock.json .
COPY ./package.json .

# install dependencies
RUN npm install
