version: 0.2

phases:
  install:
    commands:
      - echo Entered the install phase...
      - apt-get update -y
  build:
    commands:
      - echo Entered the build phase...
      - echo Build started on `date`
      - docker-compose build
  post_build:
    commands:
      - echo Entered the post_build phase...
      - docker-compose up
      - echo Build completed on `date`
